server:
  port: 8080
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: DEBUG

